import { Job, Provider, PanicAlert, Notification, User } from '../types';

export const mockProviders: Provider[] = [
  {
    id: 'p1',
    name: 'Sipho Dlamini',
    email: 'sipho@example.com',
    phone: '+27 82 345 6789',
    role: 'provider',
    trade: 'plumbing',
    rating: 4.8,
    jobsCompleted: 134,
    responseTime: '< 15 min',
    verificationLevel: 2,
    subscriptionTier: 'active',
    leadsUsed: 22,
    earnings: 18450,
    rankScore: 92,
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'p2',
    name: 'Thandi Mokoena',
    email: 'thandi@example.com',
    phone: '+27 76 234 5678',
    role: 'provider',
    trade: 'electrical',
    rating: 4.9,
    jobsCompleted: 98,
    responseTime: '< 10 min',
    verificationLevel: 3,
    subscriptionTier: 'active',
    leadsUsed: 18,
    earnings: 22100,
    rankScore: 97,
    isActive: true,
    createdAt: '2024-02-20',
  },
  {
    id: 'p3',
    name: 'Bongani Nkosi',
    email: 'bongani@example.com',
    phone: '+27 71 456 7890',
    role: 'provider',
    trade: 'mechanical',
    rating: 4.5,
    jobsCompleted: 67,
    responseTime: '< 30 min',
    verificationLevel: 1,
    subscriptionTier: 'free',
    leadsUsed: 4,
    earnings: 9800,
    rankScore: 78,
    isActive: true,
    createdAt: '2024-03-10',
  },
  {
    id: 'p4',
    name: 'Nomsa Khumalo',
    email: 'nomsa@example.com',
    phone: '+27 83 567 8901',
    role: 'provider',
    trade: 'plumbing',
    rating: 4.7,
    jobsCompleted: 211,
    responseTime: '< 20 min',
    verificationLevel: 2,
    subscriptionTier: 'active',
    leadsUsed: 31,
    earnings: 29750,
    rankScore: 88,
    isActive: true,
    createdAt: '2023-11-05',
  },
];

export const mockJobs: Job[] = [
  {
    id: 'j1',
    consumerId: 'c1',
    consumerName: 'Lerato Sithole',
    providerId: 'p1',
    providerName: 'Sipho Dlamini',
    category: 'plumbing',
    title: 'Burst Pipe - Kitchen',
    description: 'Kitchen pipe burst, water flooding under the sink. Urgent.',
    location: 'Sandton, Johannesburg',
    status: 'in-progress',
    price: 650,
    createdAt: '2026-03-09T08:30:00',
    acceptedAt: '2026-03-09T08:45:00',
    isEmergency: true,
  },
  {
    id: 'j2',
    consumerId: 'c2',
    consumerName: 'Naledi Phiri',
    providerId: 'p2',
    providerName: 'Thandi Mokoena',
    category: 'electrical',
    title: 'DB Board Trip – No Power',
    description: 'Main DB board keeps tripping. Need urgent assessment.',
    location: 'Rosebank, Johannesburg',
    status: 'accepted',
    price: 480,
    createdAt: '2026-03-09T09:00:00',
    acceptedAt: '2026-03-09T09:15:00',
  },
  {
    id: 'j3',
    consumerId: 'c3',
    consumerName: 'Zanele Dube',
    category: 'mechanical',
    title: 'Car Won\'t Start – Dead Battery',
    description: 'Car battery dead, need jumpstart or replacement at home.',
    location: 'Fourways, Johannesburg',
    status: 'pending',
    createdAt: '2026-03-09T10:20:00',
  },
  {
    id: 'j4',
    consumerId: 'c1',
    consumerName: 'Lerato Sithole',
    providerId: 'p1',
    providerName: 'Sipho Dlamini',
    category: 'plumbing',
    title: 'Geyser Replacement',
    description: 'Old geyser needs full replacement. 150L geyser.',
    location: 'Sandton, Johannesburg',
    status: 'completed',
    price: 4200,
    rating: 5,
    review: 'Sipho was professional and fast. Highly recommended!',
    createdAt: '2026-02-28T14:00:00',
    completedAt: '2026-02-28T17:30:00',
  },
  {
    id: 'j5',
    consumerId: 'c4',
    consumerName: 'Precious Mahlangu',
    category: 'electrical',
    title: 'Outdoor Light Installation',
    description: 'Need 4 outdoor LED lights installed around the property.',
    location: 'Midrand, Johannesburg',
    status: 'pending',
    createdAt: '2026-03-09T11:00:00',
  },
];

export const mockPanicAlerts: PanicAlert[] = [
  {
    id: 'pa1',
    userId: 'c1',
    userName: 'Lerato Sithole',
    jobId: 'j1',
    location: 'Sandton, Johannesburg',
    timestamp: '2026-03-09T09:58:00',
    status: 'active',
    latitude: -26.107,
    longitude: 28.056,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    title: 'New Job Request',
    message: 'Zanele Dube needs a mechanic in Fourways.',
    type: 'info',
    read: false,
    timestamp: '2026-03-09T10:20:00',
  },
  {
    id: 'n2',
    title: '⚠️ PANIC ALERT',
    message: 'Lerato Sithole triggered a panic alert at Sandton.',
    type: 'danger',
    read: false,
    timestamp: '2026-03-09T09:58:00',
  },
  {
    id: 'n3',
    title: 'Job Completed',
    message: 'Sipho Dlamini completed Geyser Replacement.',
    type: 'success',
    read: true,
    timestamp: '2026-02-28T17:30:00',
  },
];

export const mockConsumer: User = {
  id: 'c1',
  name: 'Lerato Sithole',
  email: 'lerato@example.com',
  phone: '+27 79 123 4567',
  role: 'consumer',
  isActive: true,
  createdAt: '2025-06-01',
};

export const mockAdminUser: User = {
  id: 'admin1',
  name: 'Admin User',
  email: 'admin@fixaapp.co.za',
  phone: '+27 11 000 0001',
  role: 'admin',
  isActive: true,
  createdAt: '2024-01-01',
};

export const mockProviderUser: User = {
  id: 'p1',
  name: 'Sipho Dlamini',
  email: 'sipho@example.com',
  phone: '+27 82 345 6789',
  role: 'provider',
  isActive: true,
  createdAt: '2024-01-15',
};
